### ISSUE TITLE
object 'chans' not found while applying compensation

### ISSUE THREAD

**Issue by cleanylee** [DillonHammill/CytoExploreR#128] opened 2022-01-12 16:19 UTC
Hi @DillonHammill , thanks for the great package. 

I tried to do compensation with the package and encountered some issues I couldn't figure out why.
The error message happens when I tried to run cyto_plot_compensation or cyto_compensate

I followed the code of example article and also get the same error. (shown below)

Code:
![image](https://user-images.githubusercontent.com/54748010/149180281-98570583-cd16-4aab-890c-01751d50a515.png)

The Console:
![image](https://user-images.githubusercontent.com/54748010/149178034-f9e1e4de-c119-43b7-892c-019119a1e544.png)

**Comment by williamsdrake** [comment] 2022-01-12 17:30
Just ran into this problem as well. Following the vignette and sample data

```
> # Apply compensation
> gs <- cyto_compensate(gs,
+                       spillover = "Spillover-Matrix.csv")
Error in colnames(z) %in% chans : object 'chans' not found
> traceback()
6: colnames(z) %in% chans
5: which(!colnames(z) %in% chans)
4: FUN(X[[i]], ...)
3: lapply(spill, function(z) {
       cols_rm <- which(!colnames(z) %in% chans)
       if (length(cols_rm) > 0) {
           z <- z[, -cols_rm]
           row_rm <- LAPPLY(cols_rm, function(w) {
               which(z[, w] == 1)
           })
           row_rm <- row_rm[!is.na(row_rm)]
           if (length(row_rm) > 0) {
               z <- z[-row_rm, ]
           }
       }
       return(z)
   })
2: cyto_compensate.GatingSet(gs, spillover = "Spillover-Matrix.csv")
1: cyto_compensate(gs, spillover = "Spillover-Matrix.csv")
```

It appears the problem is within the function cyto_compensate.GatingSet.

**Comment by DillonHammill** [comment] 2022-01-12 19:40
Apologies for not spotting this bug sooner, I have been working on getting the new version of CytoExploreR (v2.0.0) ready for release - if all goes to plan it should be available next week.

In the meantime, I have pushed a fix to the `master` branch on GitHub to fix this issue in version 1.1.0 of CytoExploreR. Please pull down the latest version from GitHub and let me know how you go.
```{r}
devtools::install_github("DillonHammill/CytoExploreR")
```

**Comment by williamsdrake** [comment] 2022-01-13 03:48
No need to apologize. It is working for me now after pulling the latest version. Just saw some tweets about v2, looking forward to it!

**Comment by cleanylee** [comment] 2022-01-13 17:39
Thanks @DillonHammill 
It works perfectly now after the update. Looking forward to the new version !

**Closed** 2022-01-13 17:40 UTC
Labels: Bug
