### ISSUE TITLE
How does 'alias' calculate statistics in 1D cyto_plot?

### ISSUE THREAD

**Issue by northNomad** [DillonHammill/CytoExploreR#7] opened 2020-02-21 16:17 UTC
I used ```rectangleGate``` from ```flowCore``` to make a 1D gate on channel FL4.H -
The channel FL4.H stains for a surface marker called "Gr1". 
And I call the gate ```Gr1 +```.

When I plot 1D graph using ```cyto_plot``` and use the ```alias``` argument to display the gate and stats; it shows this:
```
cyto_plot(gs[c(2,3,4,6,7,8)], 
          parent = "liveCells",
          channels = "FL4.H",
          group_by = c("Sample", "Treatment"),
          density_stack = .5,
          legend = TRUE,
          title = "Clec5A KD in IVO/DMSO",
          xlab = "FL4.H - Gr1",
          ylab = "Modal",
          alias = "Gr1 +"
)
```
![1D](https://user-images.githubusercontent.com/60832021/75051080-3db29800-549b-11ea-98db-d791e3e90bd9.jpeg)

But when I use it in 2D by plotting ```FL4.H``` vs ```FSC.A```, I get this:
```
cyto_plot(gs[c(2,3,4,6,7,8)], 
          parent = "liveCells",
          channels = c("FL4.H", "FSC.A"),
          group_by = c("Sample", "Treatment"),
          axes_limits = "data", 
          alias = "Gr1 +",
          layout = c(3,2)
)
```
![2D](https://user-images.githubusercontent.com/60832021/75051191-6b97dc80-549b-11ea-9324-c659cc0d29f0.jpeg)

As you can see: the stats are drastically different.
I know that the stat/percentage shown from the 2D plot is correct.
Just wondering how alias calculates the stats in 1D plot?

Many thanks -
Very impressed with the package so far.

**Comment by DillonHammill** [comment] 2020-02-21 21:27
Thanks for reporting @northNomad!

Alright, a number of things are happening here. Firstly, the data is being grouped and merged into your experimental groups. The data in each group is then down sampled to 25000 events using the default display setting of cyto_plot. Then the 1D gate is converted to a 2D gate (infinite coords in the second channel) and applied to the data.

I suspect that the difference in statistics is to do with how the data is sampled. To check this, please can you re-plot the data without sampling (i.e. set the display argument to 1) and include the plots so I can take a look?

Cheers,
Dillon

**Comment by northNomad** [comment] 2020-02-22 04:04
> Thanks for reporting @northNomad!
> 
> Alright, a number of things are happening here. Firstly, the data is being grouped and merged into your experimental groups. The data in each group is then down sampled to 25000 events using the default display setting of cyto_plot. Then the 1D gate is converted to a 2D gate (infinite coords in the second channel) and applied to the data.
> 
> I suspect that the difference in statistics is to do with how the data is sampled. To check this, please can you re-plot the data without sampling (i.e. set the display argument to 1) and include the plots so I can take a look?
> 
> FYI you can use cyto_plot_save() to save high resolution images. Try running this and then making the call to cyto_plot:
> 
> ```
> cyto_plot_save("1D-plot.png")
> ```
> 
> This will save the plot to a 7 x 7 inch png. You can change the size of the image using the height and with arguments (e.g. `height = 9` and `width = 6` for the 2D plot).
> 
> Cheers,
> Dillon

@DillonHammill ,
Some additional info/questions:
1. Although I used the ```group_by``` argument, all my groups only have one sample. I was just trying to test out the code.
2. According to the instruction, ```label =``` in ```cyto_plot``` takes a boolean argument!? What does it mean by using ```label = 1```?
Is it such that if I have multiple samples in a group (like I should have/how ```group_by``` argument is intended), I can use ```label = 1``` to display only the first sample's statistics?

Anyhow, followed your instruction:
```
cyto_plot_save("1D plot.png")

cyto_plot(gs[c(2,3,4,6,7,8)], 
          parent = "liveCells",
          channels = "FL4.H",
          group_by = c("Sample", "Treatment"),
          density_stack = .5,
          legend = TRUE,
          title = "Clec5A KD in IVO/DMSO",
          xlab = "FL4.H - Gr1",
          ylab = "Modal",
          alias = "Gr1 +",
          label = 1
)
```
![1D plot](https://user-images.githubusercontent.com/60832021/75086027-8c911980-54fd-11ea-81af-a572798b89db.png)


-->My intuition: below is a screenshot of page23 in Wickham's ggplot2 - Elegant Graphics for Data Analysis.
Is there an inherent problem in calculating ```stats``` from density plots because of the smoothness assumption?
If that's the case, calculating ```stats``` from histogram should work fine - unfortunately I cannot test that out using ```cyto_plot``` (at least I'm not aware).
![Untitled](https://user-images.githubusercontent.com/60832021/75086105-5dc77300-54fe-11ea-8f20-5b0e8176dada.png)

Many thanks again!

**Comment by DillonHammill** [comment] 2020-02-22 04:08
Sorry I was not clear, set `display = 1`. The display argument controls the degree of sampling in cyto_plot.

**Comment by northNomad** [comment] 2020-02-22 04:57
> Sorry I was not clear, set `display = 1`. The display argument controls the degree of sampling in cyto_plot. The `label` argument simply turns the labels on and off.
> 
> As far as I know, the smoothness should not affect the gating. I want rule out the sampling before looking into that. I will play around with it later today.

Appreciate the clarification - Now I remember. You explained it perfectly in the Article **Viualise Cytometry Data with cyto_plot()**

So below I set the ```label``` to ```1``` ```0.5``` and ```1000```:
Only sampling all the events does the plot display a stat/label.

![Plot1](https://user-images.githubusercontent.com/60832021/75086780-ea296400-5505-11ea-8bbc-b7443589cde4.png)
![Plot](https://user-images.githubusercontent.com/60832021/75086781-ec8bbe00-5505-11ea-8adc-eda55b5bf219.png)
![Plot2](https://user-images.githubusercontent.com/60832021/75086782-edbceb00-5505-11ea-8de3-dc6932875c63.png)

**Comment by DillonHammill** [comment] 2020-02-22 08:07
OK, not sure why you continue to change the `label` argument instead of the `display` argument. Anyways here is some of the testing that I have done.

To test this I used the Activation samples (each contain 50000 events) and added a 1-D threshold gate using `cyto_gate_draw` as below:

```{r}
library(CytoExploreRData)
library(CytoExploreR)

fs <- Activation
gs <- GatingSet(fs)
cyto_compensate(gs)
cyto_transform(gs)

# Construct 1-D open ended 1-D gate
cyto_gate_draw(gs,
               parent = "root",
               alias = "T Cells",
               channels = "Va2",
               gatingTemplate = "Test.csv",
               type = "t")
```

If we plot the gate in 1-D this is what we get with the default `display = 25000` (i.e. each layer will be down sampled to 25000 events):

```{r}
cyto_plot(gs[29:32],
          parent = "root",
          alias = "T Cells",
          channels = "Va2",
          density_stack = 0.5)
```

![1D-25000](https://user-images.githubusercontent.com/28646736/75088521-7ee19f80-55a2-11ea-9c98-83dc3f7e8554.png)

If we then plot the gate in 2-D this is what we get with the default `display = 25000` (i.e. each layer will be down sampled to 25000 events):

```{r}
cyto_plot(gs[29:32],
          parent = "root",
          alias = "T Cells",
          channels = c("Va2","FSC-A"))
```

![2D-25000](https://user-images.githubusercontent.com/28646736/75088543-d718a180-55a2-11ea-8529-5eca9a68a790.png)

Hopefully you agree that there is no difference in the calculated statistics for both 1-D and 2-D plots. Now let's try and display all 50000 events to see how this impacts the statistic. 

Here is the 1-D plot with `display = 1` to display all 50000 events:

```{r}
cyto_plot(gs[29:32],
          parent = "root",
          alias = "T Cells",
          channels = "Va2",
          density_stack = 0.5,
          display = 1)
```

![1D-50000](https://user-images.githubusercontent.com/28646736/75088573-5017f900-55a3-11ea-80db-fb22492bec9d.png)

Notice how these statistics are slightly different to the previous plots. That's because we are now using twice as many events - the statistics in this plot are therefore more accurate.

Next, let's see what the statistics look like in 2-D plots with `display = 1` to display all 50000 events:

```{r}
cyto_plot(gs[29:32],
          parent = "root",
          alias = "T Cells",
          channels = c("Va2","FSC-A"),
          display = 1)
```

![2D-50000](https://user-images.githubusercontent.com/28646736/75088600-b56bea00-55a3-11ea-912a-4b7451865eec.png)

As you can see the statistics in 1-D or 2-D plots are always in agreement. The statistics only change when the number of events used to calculate the statistic changes (as we would expect).

Lastly, let's check if the degree of smoothing affects the calculated statistic by setting `density_smooth = 0.2`:

```{r}
cyto_plot(gs[29:32],
          parent = "root",
          alias = "T Cells",
          channels = "Va2",
          density_stack = 0.5,
          display = 1)
```
![1D-50000-smooth](https://user-images.githubusercontent.com/28646736/75088647-417e1180-55a4-11ea-99ab-ca338ef81abb.png)

As you can see that statistics are identical to those where `density_smooth = 0.6` in the previous 1-D plot. The smoothness of the distribution only changes how the data is visualized but does not alter the calculated statistic. However,
if `density_smooth` is set incorrectly, this may alter where the initial gate is positioned and therefore alter the calculated statistic. I have therefore spent a lot of time optimising this parameter, and arrived at a default of `density_smooth = 0.6` to best display the data.

So it looks like something else must be going wrong with plotting your data, I suspect it may be an issue with `group_by`. I will look into this.

NOTE: `group_by` is designed for displaying mean statistics for experimental replicates by merging samples. If you want to display individual samples you will need to specify their indices manually (e.g. gs[c(31,32,33,34)]) or use `cyto_select` to pull out a subset of samples. 

Here is an example using the Activation dataset. If we only wanted to plot the samples related to the Stim-A treatment group, we can pull them out using `cyto_select()` and then plot them using `cyto_plot()`.

```{r}
gs_stimA <- cyto_select(gs, Treatment = "Stim-A")

cyto_plot(gs_stimA,
                parent = "root",
                alias = "T Cells",
                channels = "Va2",
                density_stack = 0.5,
                display = 1)
```

![1D-select](https://user-images.githubusercontent.com/28646736/75088792-067cdd80-55a6-11ea-9f38-564e1ed22fe3.png)

Hope this helps to clarify things!

**Comment by northNomad** [comment] 2020-02-22 17:08
Legendary - 
Appreciate the guidance / apologize for my entry-level mistakes

**Comment by DillonHammill** [comment] 2020-02-22 23:59
No problem at all! 

I have also checked that the statistics remain unchanged when individual samples are grouped using the `group_by` argument:

```{r}
# No grouping
cyto_plot(gs[c(8, 16, 24, 32)],
          parent = "root",
          channels = c("Va2", "FSC-A"),
          alias = "T Cells",
          display = 1)
```
![2D-ungrouped](https://user-images.githubusercontent.com/28646736/75101028-a2e8c380-562a-11ea-911e-3632b6b32cea.png)

```{r}
# Grouping
cyto_plot(gs[c(8, 16, 24, 32)],
          parent = "root",
          channels = c("Va2", "FSC-A"),
          alias = "T Cells",
          group_by = "Treatment",
          display = 1)
```
![2D-grouped](https://user-images.githubusercontent.com/28646736/75101029-a714e100-562a-11ea-982a-a4bbb8b06ef8.png)

As you can see the statistics are the same. I also checked the 1-D plots and the statistics are identical. 

So I will reopen this issue as I still don't know why the statistics are different in your case. Could you please try plotting the following using your samples and include the plots here so I can take a look?

```[r]
# 1D with grouping
cyto_plot(gs[c(2,3,4,6,7,8)], 
          parent = "liveCells",
          channels = "FL4.H",
          group_by = c("Sample", "Treatment"),
          density_layers = 1,
          alias = "Gr1 +"
)
```

```[r]
# 1D without grouping
cyto_plot(gs[c(2,3,4,6,7,8)], 
          parent = "liveCells",
          channels = "FL4.H",
          density_layers = 1,
          alias = "Gr1 +"
)
```

```{r}
# 2D with grouping
cyto_plot(gs[c(2,3,4,6,7,8)], 
          parent = "liveCells",
          channels = c("FL4.H", "FSC.A"),
          group_by = c("Sample", "Treatment"),
          alias = "Gr1 +"
)
```

```{r}
# 2D without grouping
cyto_plot(gs[c(2,3,4,6,7,8)], 
          parent = "liveCells",
          channels = c("FL4.H", "FSC.A"),,
          alias = "Gr1 +"
)
```

Thanks for your help :)

**Comment by northNomad** [comment] 2020-03-12 21:27
Sorry for delaying on this - 
Caught up by something else these past weeks.
Will make sure to update this weekend.

**Comment by northNomad** [comment] 2020-03-28 22:48
I've uploaded an example:

1. The .csv file is the ```gatingTemplate```.
2. The ```R script``` is code to reproduce the example. Set up the gating set with the ```7 fcs files``` and apply the ```gatingTemplate```.  

https://github.com/northNomad/cyto_plot.Troubleshoot/tree/master/exampleFiles

NN

**Comment by DillonHammill** [comment] 2020-03-29 00:03
Thanks I will take a look when I get some time.

**Comment by Mieszkol** [comment] 2020-04-28 12:02
Hi, 
I've got a similar problem to northNomad. After setting up some preliminary gates, I gated on CD2 and CD56 using a rectangle gate:

> cyto_gate_draw(gs, parent = "NK", alias = "143Nd_CD2", channels = c("143Nd_CD2", "176Lu_CD56"), type = "rectangle", select = 1)

Then I wanted to plot some histograms using the 2D gates I already made but the percentages were off 

![1D](https://user-images.githubusercontent.com/61295680/80483950-36a27d00-8957-11ea-8dd6-6c46cc1266b8.png)
![2D](https://user-images.githubusercontent.com/61295680/80484809-9f3e2980-8958-11ea-824e-e368563a2760.png)



> cyto_plot(gs[1:6], parent = "NK", 
>           alias = "143Nd_CD2", channels = "143Nd_CD2",
>           density_smooth = 0.4,
>           density_layers = 6, 
>           density_stack = 0.7, # 50% stacking
>           density_modal = TRUE,
>           density_fill = c("#f1eef6","#d0d1e6","#a6bddb","#74a9cf","#2b8cbe","#045a8d"),
>           density_fill_alpha = c(0.75, 0.8, 0.85, 0.9, 0.95, 1),
>           display = 1
> )
> 
> cyto_plot(gs[1:6], parent = "NK", 
>           alias = "143Nd_CD2", channels = c("143Nd_CD2","176Lu_CD56"),
>           display = 1,
>           title = NA
>           
> )


As you can see the percentage of CD2+ cells is over 100 in one sample although the same parent gate was used both for 1D plotting and for setting the gate.

Could you please explain where I've made a mistake? Thank you!

Best
Mieszko

**Comment by DillonHammill** [comment] 2020-04-28 12:15
Very strange. I have never seen statistics over 100%. Do you mind providing some code so that I can reproduce this? I will look into this in detail tomorrow to see if I can figure out what is going on.

**Comment by Mieszkol** [comment] 2020-04-28 12:41
![1D](https://user-images.githubusercontent.com/61295680/80488102-217d1c80-895e-11ea-8f6c-375aa928c363.png)


![2D](https://user-images.githubusercontent.com/61295680/80488119-28a42a80-895e-11ea-9909-b08677af86c5.png)

I guess something is wrong with stacking. Anyway, here is the code:

```
library(flowCore)
library(flowWorkspace)
library(openCyto)
library(ggcyto)
library(CytoExploreR)
library(CATALYST)
library(premessa)

setwd(dir = "/Volumes/ML_8TB/Cloud/ScienceData/CyTOF/XXXX/P1/ANALYSIS/R/")

gs <- cyto_setup(path = ("/Volumes/ML_8TB/Cloud/ScienceData/CyTOF/XXXX/P1/ANALYSIS/Single"), gatingTemplate = "XXXX.csv")

cyto_gatingTemplate_apply(gs, "XXXX.csv") 

# Apply data transformations
gs <- cyto_transform(gs, type = "arcsinh") 

#Draw gates
cyto_gate_draw(gs, parent = "root", alias = "Cells", channels = c("151Eu_CXCR4_EQ", "153Eu_TIM-3_EQ"), type = "rectangle")
cyto_gate_draw(gs, parent = "Cells", alias = "Single Cells", channels = c("191Ir_Ir-191", "Event_length"))
cyto_gate_draw(gs, parent = "Single Cells", alias = "LiveCD45+", channels = c("89Y_CD45", "103Rh_Intercalator"), type = "rectangle")
cyto_gate_draw(gs, parent = "LiveCD45+", alias = "NK", channels = c("148Nd_CD3_CD14_CD19", "176Lu_CD56"), type = "rectangle")
cyto_gate_draw(gs, parent = "NK", alias = "143Nd_CD2", channels = c("143Nd_CD2", "176Lu_CD56"), type = "rectangle", select = 1)

#Edit gates
cyto_gate_edit(gs, parent = "root", alias = "Cells", channels = c("151Eu_CXCR4_EQ", "153Eu_TIM-3_EQ"), type = "rectangle")
cyto_gate_edit(gs, parent = "Cells", alias = "Single Cells", channels = c("191Ir_Ir-191", "Event_length"))
cyto_gate_edit(gs, parent = "Single Cells", alias = "LiveCD45+", channels = c("89Y_CD45", "103Rh_Intercalator"), type = "rectangle")
cyto_gate_edit(gs, parent = "LiveCD45+", alias = "NK", channels = c("148Nd_CD3_CD14_CD19", "176Lu_CD56"), type = "rectangle")
cyto_gate_edit(gs, parent = "NK", alias = "143Nd_CD2", channels = c("143Nd_CD2", "176Lu_CD56"), type = "rectangle", select = 1)

#Plots
cyto_plot(gs[1:6], parent = "NK", 
          alias = "143Nd_CD2", channels = "143Nd_CD2",
          density_smooth = 0.4,
          density_layers = 6, 
          density_stack = 0.7,
          density_modal = TRUE,
          density_fill = c("#f1eef6","#d0d1e6","#a6bddb","#74a9cf","#2b8cbe","#045a8d"),
          density_fill_alpha = c(0.75, 0.8, 0.85, 0.9, 0.95, 1),
          display = 1
)

cyto_plot(gs[1:6], parent = "NK", 
          alias = "143Nd_CD2", channels = c("143Nd_CD2","176Lu_CD56"),
          display = 1,
          title = NA
          
)
```

**Comment by Mieszkol** [comment] 2020-04-28 12:50
I guess something is wrong with stacking, without it everything looks good. However, I still wonder what's the cause for differences between upper-middle plots (90.7 vs 90.6). display = 1 in both cases.
![1D](https://user-images.githubusercontent.com/61295680/80488518-be3fba00-895e-11ea-838a-7f5ae42537c0.png)
![2D](https://user-images.githubusercontent.com/61295680/80488527-c0a21400-895e-11ea-95b9-7b30f6ce6d7c.png)

```
library(flowCore)
library(flowWorkspace)
library(openCyto)
library(ggcyto)
library(CytoExploreR)
library(CATALYST)
library(premessa)

setwd(dir = "/Volumes/ML_8TB/Cloud/ScienceData/CyTOF/XXXX/P1/ANALYSIS/R/")

gs <- cyto_setup(path = ("/Volumes/ML_8TB/Cloud/ScienceData/CyTOF/XXXX/P1/ANALYSIS/Single"), gatingTemplate = "XXXX.csv")

cyto_gatingTemplate_apply(gs, "XXXX.csv") 

# Apply data transformations
gs <- cyto_transform(gs, type = "arcsinh") 

#Draw gates
cyto_gate_draw(gs, parent = "root", alias = "Cells", channels = c("151Eu_CXCR4_EQ", "153Eu_TIM-3_EQ"), type = "rectangle")
cyto_gate_draw(gs, parent = "Cells", alias = "Single Cells", channels = c("191Ir_Ir-191", "Event_length"))
cyto_gate_draw(gs, parent = "Single Cells", alias = "LiveCD45+", channels = c("89Y_CD45", "103Rh_Intercalator"), type = "rectangle")
cyto_gate_draw(gs, parent = "LiveCD45+", alias = "NK", channels = c("148Nd_CD3_CD14_CD19", "176Lu_CD56"), type = "rectangle")
cyto_gate_draw(gs, parent = "NK", alias = "143Nd_CD2", channels = c("143Nd_CD2", "176Lu_CD56"), type = "rectangle", select = 1)

#Edit gates
cyto_gate_edit(gs, parent = "root", alias = "Cells", channels = c("151Eu_CXCR4_EQ", "153Eu_TIM-3_EQ"), type = "rectangle")
cyto_gate_edit(gs, parent = "Cells", alias = "Single Cells", channels = c("191Ir_Ir-191", "Event_length"))
cyto_gate_edit(gs, parent = "Single Cells", alias = "LiveCD45+", channels = c("89Y_CD45", "103Rh_Intercalator"), type = "rectangle")
cyto_gate_edit(gs, parent = "LiveCD45+", alias = "NK", channels = c("148Nd_CD3_CD14_CD19", "176Lu_CD56"), type = "rectangle")
cyto_gate_edit(gs, parent = "NK", alias = "143Nd_CD2", channels = c("143Nd_CD2", "176Lu_CD56"), type = "rectangle", select = 1)

#Plots
cyto_plot(gs[1:6], parent = "NK", 
          alias = "143Nd_CD2", channels = "143Nd_CD2",
          density_smooth = 0.4,
          density_layers = 1, 
          density_stack = 0, 
          density_modal = TRUE,
          density_fill = c("#f1eef6","#d0d1e6","#a6bddb","#74a9cf","#2b8cbe","#045a8d"),
          density_fill_alpha = c(0.75, 0.8, 0.85, 0.9, 0.95, 1),
          display = 1, 
          title = NA
)

cyto_plot(gs[1:6], parent = "NK", 
          alias = "143Nd_CD2", channels = c("143Nd_CD2","176Lu_CD56"),
          display = 1,
          title = NA
          
)
```

**Comment by DillonHammill** [comment] 2020-04-29 02:23
I have found the bug! Working on a fix now. Please avoid using the `density_stack` feature until this is fixed.

**Comment by northNomad** [comment] 2020-04-29 03:49
> I have found the bug! Working on a fix now. Please avoid using the `density_stack` feature until this is fixed.

Thank you so much for being amazing

**Comment by DillonHammill** [comment] 2020-04-29 05:32
@northNomad & @Mieszkol, I just pushed the fix for the statistics in stacked density distributions. This was a really tricky bug to find, so thank you for reporting this. 

Please install the latest version from GitHub:
```{r}
devtools::install_github("DillonHammill/CytoExploreR")
```

Or update your docker image from the command prompt/terminal:
```{r}
docker pull dhammill/cytoexplorer:latest
```

This feature is designed to help give a quick visualization of the data in 1-D without having to draw a separate 1-D gate. There are a couple of caveats to its use:
* The statistics in the 1-D plots are likely to be different than those in the 2-D plots. The reason for this is that events outside a 2-D gate but within the bounds of the 1-D gate will be included in 1-D gate. For example, @Mieszkol in the second panel of 2D plots you will notice some events above the 2-D gate. When you convert the gate into a 1-D, these events are still within the bounds on the x axis and will therefore be counted inside the 1-D gate. This is why there is a slight difference between the 1-D and 2-D statistics for this sample. You will notice that all other samples have a 2-D gate that already encompasses all the events and so the 1-D and 2-D statistics are identical. 
* This feature works best with 2-D interval gates. If you want the statistics to be identical for both 2-D and 1-D gates, you should use interval gates as they are essentially 1-D gates with infinite boundaries in the second channel. In your case @Mieszkol, a 2-D interval gate would capture all events within the x axis boundaries and so this statistic will match that of the constructed 1-D gate.

Please let me know if this is still unclear. 

There are number of additional improvements to `cyto_plot` that will be available when you update CytoExploreR. Please let me know if anything is not working as you would expect. I will release the new version tomorrow.

On a separate note @Mieszkol, make sure that you perform the data transformations prior to gating. The gate co-ordinates are on the transformed scale and so it is not a good idea to apply gates to untransformed data

**Comment by northNomad** [comment] 2020-04-29 16:25
> I've uploaded an example:
> 
> 1. The .csv file is the `gatingTemplate`.
> 2. The `R script` is code to reproduce the example. Set up the gating set with the `fcs files` and apply the `gatingTemplate`.
> 
> https://github.com/northNomad/cyto_plot.Troubleshoot/tree/master/exampleFiles
> 
> NN

@DillonHammill 

The problem appears to be fixed. 
I ran my previous error example files and it's working perfectly now!

2D:
![image](https://user-images.githubusercontent.com/60832021/80620672-4a5fe900-8a14-11ea-8da5-6bd5a9c6aa0c.png)

1D:
![image](https://user-images.githubusercontent.com/60832021/80620703-5350ba80-8a14-11ea-8b91-23380165377b.png)

Thanks a lot again @DillonHammill @Mieszkol

**Comment by DillonHammill** [comment] 2020-04-29 17:22
Fantastic!

**Comment by Mieszkol** [comment] 2020-04-30 10:45
Hi, for me the problem is also fixed. Thank you so much for such a fast response!

**Comment by DillonHammill** [comment] 2020-04-30 10:51
Excellent! Thanks again for the reporting this.

**Closed** 2020-04-30 10:51 UTC
Labels: Bug, Feedback Wanted
